from __future__ import annotations
import importlib

CAPABILITY_MODULES = [
    'nova.capabilities.memory.preference_memory',
    'nova.capabilities.memory.goal_memory',
    'nova.capabilities.memory.workflow_memory',
    'nova.capabilities.memory.project_history',
    'nova.capabilities.memory.privacy_export',
    'nova.capabilities.memory.memory_pruning',
    'nova.capabilities.memory.semantic_recall',
    'nova.capabilities.memory.memory_review',
    'nova.capabilities.documents.pdf_qa',
    'nova.capabilities.documents.docx_qa',
    'nova.capabilities.documents.markdown_notes',
    'nova.capabilities.documents.table_extraction',
    'nova.capabilities.documents.flashcards',
    'nova.capabilities.documents.study_notes',
    'nova.capabilities.documents.document_compare',
    'nova.capabilities.documents.deadline_extractor',
    'nova.capabilities.documents.quote_citations',
    'nova.capabilities.documents.folder_qa',
    'nova.capabilities.files.filename_search',
    'nova.capabilities.files.semantic_file_search',
    'nova.capabilities.files.duplicate_detection',
    'nova.capabilities.files.large_file_audit',
    'nova.capabilities.files.old_file_audit',
    'nova.capabilities.files.safe_organize',
    'nova.capabilities.files.undo_restore',
    'nova.capabilities.files.workspace_creator',
    'nova.capabilities.files.temp_file_detector',
    'nova.capabilities.files.download_triage',
    'nova.capabilities.automation.open_application',
    'nova.capabilities.automation.open_folder',
    'nova.capabilities.automation.create_workspace',
    'nova.capabilities.automation.safe_shell_review',
    'nova.capabilities.automation.screenshot_capture',
    'nova.capabilities.automation.approved_script_runner',
    'nova.capabilities.automation.process_status',
    'nova.capabilities.automation.desktop_shortcuts',
    'nova.capabilities.coding.project_scaffold',
    'nova.capabilities.coding.fastapi_generator',
    'nova.capabilities.coding.cli_generator',
    'nova.capabilities.coding.test_writer',
    'nova.capabilities.coding.readme_writer',
    'nova.capabilities.coding.code_reviewer',
    'nova.capabilities.coding.security_review',
    'nova.capabilities.coding.architecture_summary',
    'nova.capabilities.coding.bug_hunter',
    'nova.capabilities.coding.refactor_plan',
    'nova.capabilities.data.csv_profile',
    'nova.capabilities.data.json_profile',
    'nova.capabilities.data.missing_values',
    'nova.capabilities.data.duplicate_rows',
    'nova.capabilities.data.statistics_report',
    'nova.capabilities.data.chart_plan',
    'nova.capabilities.data.data_quality',
    'nova.capabilities.data.export_report',
    'nova.capabilities.voice.push_to_talk',
    'nova.capabilities.voice.offline_stt',
    'nova.capabilities.voice.offline_tts',
    'nova.capabilities.voice.wakeword_future',
    'nova.capabilities.voice.noise_handling',
    'nova.capabilities.voice.voice_privacy',
    'nova.capabilities.productivity.tasks',
    'nova.capabilities.productivity.reminders',
    'nova.capabilities.productivity.calendar_export',
    'nova.capabilities.productivity.daily_plan',
    'nova.capabilities.productivity.weekly_review',
    'nova.capabilities.productivity.study_schedule',
    'nova.capabilities.productivity.exam_quiz',
    'nova.capabilities.productivity.report_builder',
    'nova.capabilities.system.cpu_monitor',
    'nova.capabilities.system.ram_monitor',
    'nova.capabilities.system.disk_monitor',
    'nova.capabilities.system.model_status',
    'nova.capabilities.system.plugin_status',
    'nova.capabilities.system.audit_viewer',
    'nova.capabilities.system.settings_manager',
    'nova.capabilities.system.health_check',
    'nova.capabilities.plugins.plugin_loader',
    'nova.capabilities.plugins.permission_model',
    'nova.capabilities.plugins.plugin_logs',
    'nova.capabilities.plugins.disable_plugin',
    'nova.capabilities.plugins.dashboard_panel',
    'nova.capabilities.plugins.tool_registry',
    'nova.capabilities.plugins.workflow_pack',
    'nova.capabilities.plugins.capability_catalog',
]

def load_capabilities():
    caps=[]
    for module_name in CAPABILITY_MODULES:
        mod=importlib.import_module(module_name)
        caps.append(mod.create_capability())
    return caps

def capability_index():
    return {c.spec.name: c.describe() for c in load_capabilities()}
