from __future__ import annotations

from pathlib import Path

from nova.core.paths import nova_home
from nova.plugins.base import NovaPlugin, PluginManifest, PluginResult


class CodeProjectPlugin(NovaPlugin):
    manifest = PluginManifest("code_project", "Generate safe local Python project templates", ["files:write"])

    def commands(self) -> dict[str, str]:
        return {"python-cli": "Create a Python CLI project skeleton under NOVA workspaces"}

    def run(self, command: str, argument: str) -> PluginResult:
        if command != "python-cli":
            return PluginResult(False, f"Unknown code project command: {command}")
        slug = "".join(ch if ch.isalnum() or ch in "-_" else "-" for ch in (argument.strip() or "nova-project").lower()).strip("-")
        root = nova_home() / "workspaces" / slug
        pkg = root / slug.replace("-", "_")
        pkg.mkdir(parents=True, exist_ok=True)
        (pkg / "__init__.py").write_text("__version__ = '0.1.0'\n", encoding="utf-8")
        (pkg / "cli.py").write_text(
            "def main():\n    print('Hello from generated NOVA project')\n\nif __name__ == '__main__':\n    main()\n",
            encoding="utf-8",
        )
        (root / "README.md").write_text(f"# {argument}\n\nGenerated by NOVA Sovereign AI.\n", encoding="utf-8")
        return PluginResult(True, f"Created project at {root}", {"path": str(root)})
