from __future__ import annotations

from datetime import datetime
from pathlib import Path

from nova.core.paths import nova_home
from nova.plugins.base import NovaPlugin, PluginManifest, PluginResult


class ReportGeneratorPlugin(NovaPlugin):
    manifest = PluginManifest("report_generator", "Create local Markdown reports", ["files:write"])

    def commands(self) -> dict[str, str]:
        return {"markdown": "Create a Markdown report from provided text"}

    def run(self, command: str, argument: str) -> PluginResult:
        if command != "markdown":
            return PluginResult(False, f"Unknown report command: {command}")
        reports = nova_home() / "reports"
        reports.mkdir(parents=True, exist_ok=True)
        title = argument.strip().splitlines()[0][:80] if argument.strip() else "NOVA Report"
        path = reports / f"report-{datetime.now().strftime('%Y%m%d-%H%M%S')}.md"
        path.write_text(f"# {title}\n\nGenerated by NOVA Sovereign AI.\n\n{argument}\n", encoding="utf-8")
        return PluginResult(True, f"Report created: {path}", {"path": str(path)})
