from __future__ import annotations

from dataclasses import dataclass, asdict
from pathlib import Path
import re, json, py_compile
from nova.security.path_guard import decide_path

@dataclass(slots=True)
class ProjectFile:
    path: str
    content: str

@dataclass(slots=True)
class Blueprint:
    name: str
    kind: str
    description: str
    files: list[ProjectFile]

    def to_dict(self): return {"name": self.name, "kind": self.kind, "description": self.description, "files": [asdict(f) for f in self.files]}


def _name_from_goal(goal: str) -> str:
    m = re.search(r"called\s+([a-zA-Z][\w-]+)", goal)
    if m: return m.group(1).replace("-", "_")
    words = [w for w in re.findall(r"[A-Za-z][A-Za-z0-9_]+", goal.lower()) if w not in {"build","create","make","a","an","the","project","called"}]
    return (words[-1] if words else "nova_project").replace("-", "_")


def blueprint(goal: str) -> Blueprint:
    low = goal.lower()
    name = _name_from_goal(goal)
    if "fastapi" in low or "api" in low:
        kind = "fastapi"
        files = [
            ProjectFile("pyproject.toml", f'''[project]\nname = "{name}"\nversion = "0.1.0"\ndependencies = ["fastapi", "uvicorn"]\n'''),
            ProjectFile(f"{name}/__init__.py", ""),
            ProjectFile(f"{name}/main.py", '''from fastapi import FastAPI\n\napp = FastAPI(title="Generated by NOVA")\n\n@app.get("/health")\ndef health():\n    return {"ok": True}\n\n@app.get("/")\ndef home():\n    return {"message": "Hello from NOVA generated API"}\n'''),
            ProjectFile("tests/test_health.py", f'''from {name}.main import health\n\ndef test_health():\n    assert health()["ok"] is True\n'''),
            ProjectFile("README.md", f"# {name}\n\nGenerated FastAPI project. Run: `uvicorn {name}.main:app --reload`.\n"),
        ]
    else:
        kind = "cli"
        files = [
            ProjectFile("pyproject.toml", f'''[project]\nname = "{name}"\nversion = "0.1.0"\nrequires-python = ">=3.11"\n[project.scripts]\n{name} = "{name}.cli:main"\n'''),
            ProjectFile(f"{name}/__init__.py", '__version__ = "0.1.0"\n'),
            ProjectFile(f"{name}/cli.py", f'''import argparse\n\ndef main(argv=None):\n    parser = argparse.ArgumentParser(prog="{name}")\n    parser.add_argument("message", nargs="?", default="hello")\n    args = parser.parse_args(argv)\n    print(f"{name}: {{args.message}}")\n\nif __name__ == "__main__":\n    main()\n'''),
            ProjectFile("tests/test_cli.py", f'''from {name}.cli import main\n\ndef test_cli_runs(capsys):\n    main(["ok"])\n    assert "ok" in capsys.readouterr().out\n'''),
            ProjectFile("README.md", f"# {name}\n\nGenerated CLI project. Run: `{name} hello`.\n"),
        ]
    return Blueprint(name, kind, goal, files)


def build_project(goal: str, output_dir: str | Path, dry_run: bool = True) -> dict[str, object]:
    bp = blueprint(goal)
    dec = decide_path(output_dir, "write-project")
    if not dec.allowed: raise PermissionError(dec.reason)
    root = dec.path / bp.name
    actions = []
    for f in bp.files:
        actions.append({"write": str(root / f.path), "bytes": len(f.content.encode('utf-8'))})
    if dry_run:
        return {"dry_run": True, "blueprint": bp.to_dict(), "actions": actions}
    root.mkdir(parents=True, exist_ok=True)
    for f in bp.files:
        dest = root / f.path
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists():
            raise FileExistsError(f"Refusing to overwrite existing file: {dest}")
        dest.write_text(f.content, encoding="utf-8")
    compile_results = []
    for py in root.rglob("*.py"):
        try:
            py_compile.compile(str(py), doraise=True)
            compile_results.append({"file": str(py), "ok": True})
        except Exception as exc:
            compile_results.append({"file": str(py), "ok": False, "error": str(exc)})
    (root / "NOVA_BUILD_REPORT.json").write_text(json.dumps({"blueprint": bp.to_dict(), "compile": compile_results}, indent=2), encoding="utf-8")
    return {"dry_run": False, "root": str(root), "blueprint": bp.to_dict(), "compile": compile_results}
