from __future__ import annotations
from pathlib import Path
from nova.core.security import validate_user_path

class ProjectGenerator:
    def new(self, kind: str, path: str | Path) -> dict:
        target = validate_user_path(path, allow_missing=True)
        target.mkdir(parents=True, exist_ok=True)
        if kind == 'fastapi':
            self._fastapi(target)
        elif kind == 'cli':
            self._cli(target)
        else:
            self._python_package(target)
        return {'created': str(target), 'kind': kind}

    def _write(self, path: Path, text: str):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8')

    def _python_package(self, root: Path):
        pkg = root.name.replace('-', '_')
        self._write(root/'pyproject.toml', f'''[project]\nname = "{root.name}"\nversion = "0.1.0"\nrequires-python = ">=3.10"\n''')
        self._write(root/pkg/'__init__.py', '__version__ = "0.1.0"\n')
        self._write(root/'tests'/'test_smoke.py', f'def test_import():\n    import {pkg}\n')
        self._write(root/'README.md', f'# {root.name}\n\nGenerated by NOVA.\n')

    def _cli(self, root: Path):
        self._python_package(root)
        pkg = root.name.replace('-', '_')
        self._write(root/pkg/'cli.py', 'def main():\n    print("hello from generated CLI")\n')

    def _fastapi(self, root: Path):
        self._write(root/'pyproject.toml', '''[project]\nname = "generated-fastapi-app"\nversion = "0.1.0"\ndependencies = ["fastapi", "uvicorn"]\nrequires-python = ">=3.10"\n''')
        self._write(root/'app'/'main.py', '''from fastapi import FastAPI\napp = FastAPI(title="Generated NOVA App")\n@app.get("/health")\ndef health():\n    return {"ok": True}\n''')
        self._write(root/'README.md', '# Generated FastAPI App\n\nRun: `uvicorn app.main:app --reload`\n')
