from __future__ import annotations
from pathlib import Path

class ProjectTemplates:
    def python_cli(self, dest: str | Path, name: str) -> Path:
        root = Path(dest).expanduser().resolve()
        pkg = name.replace('-', '_')
        (root / pkg).mkdir(parents=True, exist_ok=True)
        (root / 'tests').mkdir(exist_ok=True)
        pyproject = (
            '[build-system]\n'
            'requires=["setuptools>=68"]\n'
            'build-backend="setuptools.build_meta"\n\n'
            '[project]\n'
            f'name="{name}"\n'
            'version="0.1.0"\n'
            'requires-python=">=3.10"\n\n'
            '[project.scripts]\n'
            f'{name}="{pkg}.cli:main"\n'
        )
        (root / 'pyproject.toml').write_text(pyproject, encoding='utf-8')
        (root / pkg / '__init__.py').write_text('', encoding='utf-8')
        cli = (
            'from __future__ import annotations\n\n'
            'def main() -> None:\n'
            '    print("Hello from generated CLI")\n\n'
            'if __name__ == "__main__":\n'
            '    main()\n'
        )
        (root / pkg / 'cli.py').write_text(cli, encoding='utf-8')
        (root / 'README.md').write_text(f'# {name}\n\nGenerated by NOVA.\n', encoding='utf-8')
        (root / 'tests' / 'test_basic.py').write_text('def test_basic():\n    assert True\n', encoding='utf-8')
        return root

    def fastapi_app(self, dest: str | Path, name: str) -> Path:
        root = Path(dest).expanduser().resolve()
        pkg = name.replace('-', '_')
        (root / pkg).mkdir(parents=True, exist_ok=True)
        pyproject = f'[project]\nname="{name}"\nversion="0.1.0"\ndependencies=["fastapi", "uvicorn"]\n'
        (root / 'pyproject.toml').write_text(pyproject, encoding='utf-8')
        (root / pkg / '__init__.py').write_text('', encoding='utf-8')
        main = (
            'from fastapi import FastAPI\n'
            'app = FastAPI(title="Generated API")\n\n'
            '@app.get("/health")\n'
            'def health():\n'
            '    return {"ok": True}\n'
        )
        (root / pkg / 'main.py').write_text(main, encoding='utf-8')
        (root / 'README.md').write_text(f'# {name}\n\nRun: `uvicorn {pkg}.main:app --reload`\n', encoding='utf-8')
        return root
